// Entry point for every per-tournament stats page (e.g.
// tournaments/<slug>/index.html). Identifies the current tournament from
// a <meta name="tournament-slug"> tag, looks up the matching entry in
// TOURNAMENTS, stamps the document title + page heading, then wires up
// the manifest-driven viewer.
//
// The manifest lives next to this page at ./results/manifest.json — the
// auto-manifest GitHub workflow regenerates it on every push that touches
// tournaments/<slug>/results/.

import { setupTournamentStats } from './ui/tournament-stats.js';
import { getTournamentBySlug } from './ui/roster-presets.js';
import { submitResultsLink } from './ui/submission-links.js';

const slugMeta = document.querySelector('meta[name="tournament-slug"]');
const slug = slugMeta ? slugMeta.content : '';
const tournament = getTournamentBySlug(slug);

if (tournament) {
  document.title = `${tournament.name} — Stats`;
  const heading = document.getElementById('stats-page-heading');
  if (heading) heading.textContent = tournament.name;
} else if (slug) {
  console.warn(`[stats-main] no TOURNAMENTS entry for slug "${slug}"`);
}

// Results-submission intake link (ui/submission-links.js): "Submit game
// results" with this tournament's slug prefilled. Injected from JS rather
// than written into each shell so every per-tournament page — including
// ones generated by the submission pipeline — gets it without a per-page
// HTML edit. (The "create your own tournament" link lives on the hub only.)
const statsSection = document.getElementById('tournament-stats-section');
if (statsSection && slug) {
  const submitLink = submitResultsLink(slug);
  statsSection.insertBefore(submitLink, document.getElementById('ts-status'));
  addRulesBriefingLink(statsSection, submitLink);
}

// A tournament may ship an optional rules briefing (rules-slides.html next
// to its page). Probe for it instead of hardcoding the link in the shell:
// pipeline-generated pages are copies of a built-in tournament's shell, so
// a baked-in link would point at a deck the new tournament doesn't have.
async function addRulesBriefingLink(section, beforeEl) {
  try {
    const res = await fetch('rules-slides.html', { method: 'HEAD' });
    if (!res.ok) return;
  } catch {
    return; // unreachable — just omit the link
  }
  const p = document.createElement('p');
  p.className = 'ts-intro';
  const link = document.createElement('a');
  link.href = 'rules-slides.html';
  link.textContent = 'View rules briefing →';
  p.appendChild(link);
  section.insertBefore(p, beforeEl);
}

setupTournamentStats({ manifestUrl: 'results/manifest.json' });
